train <- read.csv("https://web.njit.edu/~ts336/train.csv")
sapply(train,function(x) sum(is.na(x)))
sapply(train, function(x) length(unique(x)))
data <- subset(train,select=c('var3','var15','imp_op_var39_comer_ult3', 'imp_op_var40_ult1', 'ind_var1_0', 'ind_var8', 'ind_var26_0', 'ind_var30_0', 'ind_var30', 'ind_var40_0', 'num_var1_0','num_var5', 'num_var42', 'saldo_var1', 'saldo_var5', 'var36', 'delta_imp_reemb_var17_1y3','ind_var43_recib_ult1', 'num_ent_var16_ult1', 'num_meses_var5_ult3', 'num_meses_var8_ult3','num_meses_var39_vig_ult3', 'num_reemb_var17_ult1', 'num_var43_recib_ult1', 'var38', 'TARGET'))
dd <- data[1:38010,]
ee <- data[38011:76020,]
model <- glm(TARGET~.,family=binomial(link='logit'),data=dd)
summary(model)
anova(model, test="Chisq")
install.packages('pscl')
library(pscl)
pR2(model)
fitted.results <- predict(model,newdata=subset(ee,select=c(1:25)),type='response')
fitted.results <- ifelse(fitted.results > 0.5,1,0)
misClasificError <- mean(fitted.results != ee$TARGET)
print(paste('Accuracy',1-misClasificError))
install.packages('ROCR')
library(ROCR)
p <- predict(model, newdata=subset(ee,select=c(1:25)), type="response")
pr <- prediction(p, ee$TARGET)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc
